// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Vathana/TSC/ekycis/expo-provider-ekycis/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Vathana/TSC/ekycis/expo-provider-ekycis/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('expo-provider-ekycis', appParameters);
});
require('c:/Vathana/TSC/ekycis/expo-provider-ekycis/index.android.js');